### ISSUE TITLE
Issue when running "make setup"

### ISSUE THREAD

**Issue by GuyInHiding** [akemin-dayo/simject#56]
When I run make setup it tells me I don't have any SDKs, but I have on for iOS 13.2 and one from the simulator

**Comment by c0dine** [comment]
same here. I have had that error for half a year now with no progress

**Comment by qwertyuiop1379** [comment]
Make sure `xcode-select -p` outputs the correct location of your SDKs. If it doesn't, set it with `xcode-select -s <location>`

**Comment by PoomSmart** [comment]
@qwertyuiop1379's advice is correct.
