### ISSUE TITLE
issues when installing substrate on 2010 macbook air running macos 11 and xcode 12... safe to proceed?

### ISSUE THREAD

**Issue by andrewgordnier** [akemin-dayo/simject#66]
so i essentially can't get any of the sdks to work even though i've run the simulator before... i was able to get make setup to work by copying the iPhoneSimulator.platform folder to the directory simject was pointing to, but now when running `./configure --xcode-sdk=iphonesimulator --xcode-archs=x86_64 && make` i get the error that the iphone sdk can't be found... here's the full error statement from terminal: 
`Found cpp for 'host': /usr/bin/xcrun --sdk iphonesimulator cc -E`
`>>> /usr/bin/xcrun --sdk iphonesimulator cc -E -dM /Users/andrewgordnier/simject* Xcode SDK 'macosx' not found`
`* Xcode SDK 'macosx' not found`
`* Xcode SDK 'iphoneos' not found`
`* Xcode SDK 'iphoneos' not found`
`Found cc for 'host': /usr/bin/cc`
`Found dsymutil for 'host': /usr/bin/dsymutil`
`** Failed to locate cc`
`  note: detected cross compilation, so searched for x86_64-apple-darwin10-cc`
`** Failed to locate cc`
`  note: detected cross compilation, so searched for i386-apple-darwin10-cc`
`** Failed to locate cc`
`  note: detected cross compilation, so searched for arm-apple-darwin10-cc`
`** Failed to locate cc`
`  note: detected cross compilation, so searched for arm64-apple-darwin10-cc`
(1 failure.)
`

**Comment by PoomSmart** [comment]
Are you using the latest Theos?

**Comment by andrewgordnier** [comment]
> 
> 
> Are you using the latest Theos?

yeah i just installed theos today, just checked /bin/update-theos and it says i'm on the current version as well

**Comment by PoomSmart** [comment]
What are you trying to configure via "configure" script? To build simject, you simply need to run "make setup". Are you instead having troubles with compiling substrate/substitute?

**Comment by andrewgordnier** [comment]
i was following the guide on how to install the substrate component. i got through make setup but i had to manually move in the platforms folder to the directory it wanted for whatever reason. i would assume any problems with the substrate install are because of that

**Comment by PoomSmart** [comment]
Explain the steps that you had to do that sound as if the guidelines don't specify.

**Comment by andrewgordnier** [comment]
so my whole process was this:
install theos using the steps for macos on the theos wiki
install simject with git clone
try running make setup (it failed because it couldn't find an sdk)
go to xcode's contents, copy the platforms folder, paste it into the path that simject is trying to install from
make setup now worked, no errors
using the steps for ios 12+ and xcode 10+ i cloned substitute into the simject folder and cd ed into the substitute folder
when i tried the command that it references in the wiki `./configure --xcode-sdk=iphonesimulator --xcode-archs=x86_64 && make` i get an error that says the sdk can't be found

**Comment by PoomSmart** [comment]
Do you have Xcode installed?

**Comment by PoomSmart** [comment]
`sudo xcode-select -s /Applications/Xcode.app` and try again.

**Comment by PoomSmart** [comment]
> i was able to get make setup to work by copying the iPhoneSimulator.platform folder to the directory simject was pointing to

You shouldn't need to do any manual directory moving.

**Comment by PoomSmart** [comment]
Closed due to inactivity.
