### ISSUE TITLE
Issue when trying to MAKE SETUP

### ISSUE THREAD

**Issue by ltran-inc** [akemin-dayo/simject#67]
When I try to 'make setup' it says :

ld: building for iOS Simulator, but linking in .tbd built for macOS/Mac Catalyst, file '/Library/Developer/CommandLineTools/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [build] Error 1
make: *** [all] Error 2

**Comment by PoomSmart** [comment]
Please install Xcode.

**Comment by ltran-inc** [comment]
I already have installed Xcode and the Command Lines + SDKs

**Comment by PoomSmart** [comment]
What is the output of `xcode-select -p` on your machine?

**Comment by ltran-inc** [comment]
/Library/Developer/CommandLineTools

**Comment by PoomSmart** [comment]
`sudo xcode-select -s /Applications/Xcode.app`
