### ISSUE TITLE
error running resim

### ISSUE THREAD

**Issue by nico671** [akemin-dayo/simject#68]
`dyld: could not load inserted library '/opt/simject/simject.dylib' because no suitable image found.  Did find:
	/opt/simject/simject.dylib: mach-o, but wrong architecture

Child process terminated with signal 6: Abort trap
Error executing command, exiting.

`
on an arm64 Mac with the latest Xcode and Theos

**Comment by PoomSmart** [comment]
What's the output of `xcode-select -p` on your machine?

**Comment by nico671** [comment]
/Applications/Xcode.app/Contents/Developer

**Comment by PoomSmart** [comment]
@nico671 Could you also give me the output of `lipo -info /opt/simject/simject.dylib` ?

**Comment by nico671** [comment]
Non-fat file: /opt/simject/simject.dylib is architecture: x86_64

**Comment by EthanArbuckle** [comment]
Was that simject dylib compiled on your arm64 machine? `make setup` uses clang's target triple, which in this case should be arm64-apple-darwin*

When you run `make setup`, does it saying "Compiling simject for arn64"?

**Comment by nico671** [comment]
it says Compiling resim for x86_64-apple-darwin20.5.0

**Comment by EthanArbuckle** [comment]
can you try compiling simject manually:
```
cd simject
clang -framework Foundation -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -DDYLIB_DIR=/opt/simject -target arm64-apple-darwin20.5.0 -dynamiclib -o /opt/simject/simject.dylib
```

**Comment by EthanArbuckle** [comment]
Can you try compiling the simject dylib manually:

```
cd simject
clang simject.m -framework Foundation -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -DDYLIB_DIR='@"/opt/simject"' -target arm64-apple-darwin20.3.0 -dynamiclib -o simject.dylib
```
then run resim

**Comment by nico671** [comment]
that worked perfectly thank you
