### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by HAKODEVx** [akemin-dayo/simject#79]
help me
`Installing Substitute...
Cloning into 'substitute'...
remote: Enumerating objects: 2163, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 2163 (delta 56), reused 56 (delta 30), pack-reused 2067
Receiving objects: 100% (2163/2163), 595.35 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (1532/1532), done.
Xcode SDK platform path: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform'
Using architectures for 'host': ['x86_64']
Found cpp for 'host': /usr/bin/xcrun --sdk iphonesimulator cc -E
>>> /usr/bin/xcrun --sdk iphonesimulator cc -E -dM /opt/simject/Frameworks/substXcode SDK platform path: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform'
Using architectures for 'asm-x86_64': ['x86_64']
Xcode SDK platform path: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform'
Using architectures for 'asm-i386': ['i386']
Xcode SDK platform path: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'
Using architectures for 'asm-arm': ['armv7']
Xcode SDK platform path: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'
Using architectures for 'asm-arm64': ['arm64']
Found cc for 'host': /usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64
Found dsymutil for 'host': /usr/bin/xcrun --sdk iphonesimulator dsymutil
Found cc for 'asm-x86_64': /usr/bin/xcrun --sdk macosx cc -arch x86_64
Found cc for 'asm-i386': /usr/bin/xcrun --sdk macosx cc -arch i386
Found cc for 'asm-arm': /usr/bin/xcrun --sdk iphoneos cc -arch armv7
Found cc for 'asm-arm64': /usr/bin/xcrun --sdk iphoneos cc -arch arm64
Will build iOS bootstrap.
Writing out/main.mk
Writing Makefile
Writing config.status
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/inject.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/inject.d ./lib/darwin/inject.c
mkdir -p out/lib/cbit
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/cbit/vec.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/cbit/vec.d ./lib/cbit/vec.c
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/objc-asm.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/objc-asm.d ./lib/darwin/objc-asm.S
mkdir -p out/generated
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/generated/darwin-inject-asm.o -MMD -MF /opt/simject/Frameworks/substitute/out/generated/darwin-inject-asm.d ./generated/darwin-inject-asm.S
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/safemode-ui-hook.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/safemode-ui-hook.d ./darwin-bootstrap/safemode-ui-hook.m
mkdir -p out/lib
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/hook-functions.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/hook-functions.d ./lib/hook-functions.c
mkdir -p /opt/simject/Frameworks/substitute/out/SafetyDance.app
cp ./darwin-bootstrap/safety-dance/white.png /opt/simject/Frameworks/substitute/out/SafetyDance.app/Default@2x.png
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/find-syms.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/find-syms.d ./lib/darwin/find-syms.c
./lib/darwin/find-syms.c:249:13: warning: 'syscall' is deprecated: first
      deprecated in iOS 10.0 - syscall(2) is unsupported; please switch to a
      supported interface. For SYS_kdebug_trace use kdebug_signpost().
      [-Wdeprecated-declarations]
        if (syscall(294, &start_address)) /* shared_region_check_np */
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/unistd.h:742:6: note: 
      'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
./lib/darwin/find-syms.c:465:42: warning: incompatible integer to pointer
      conversion passing 'uint64_t' (aka 'unsigned long long') to parameter of
      type 'const void *' [-Wint-conversion]
        image = dyld4_Loader_loadAddress((uint64_t)dlhandle>>1, *dyld4_r...
                                         ^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/interpose.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/interpose.d ./lib/darwin/interpose.c
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/objc.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/objc.d ./lib/darwin/objc.c
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/read.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/read.d ./lib/darwin/read.c
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/substrate-compat.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/substrate-compat.d ./lib/darwin/substrate-compat.c
mkdir -p out/lib/darwin
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/darwin/execmem.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/darwin/execmem.d ./lib/darwin/execmem.c
mkdir -p out/lib
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/jump-dis.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/jump-dis.d ./lib/jump-dis.c
mkdir -p out/lib
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/transform-dis.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/transform-dis.d ./lib/transform-dis.c
mkdir -p out/lib
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/lib/strerror.o -MMD -MF /opt/simject/Frameworks/substitute/out/lib/strerror.d ./lib/strerror.c
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -dynamiclib -o /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/generated/darwin-inject-asm.o out/lib/darwin/find-syms.o out/lib/darwin/inject.o out/lib/darwin/interpose.o out/lib/darwin/objc-asm.o out/lib/darwin/objc.o out/lib/darwin/read.o out/lib/darwin/substrate-compat.o out/lib/darwin/execmem.o out/lib/cbit/vec.o out/lib/jump-dis.o out/lib/transform-dis.o out/lib/hook-functions.o out/lib/strerror.o -lobjc -install_name /usr/lib/libsubstitute.0.dylib -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/inject-into-launchd.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/inject-into-launchd.d ./darwin-bootstrap/inject-into-launchd.c
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -o /opt/simject/Frameworks/substitute/out/inject-into-launchd /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/darwin-bootstrap/inject-into-launchd.o -framework IOKit -framework CoreFoundation -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/posixspawn-hook.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/posixspawn-hook.d ./darwin-bootstrap/posixspawn-hook.c
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/unrestrict.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/unrestrict.d ./darwin-bootstrap/unrestrict.c
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/bundle-loader.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/bundle-loader.d ./darwin-bootstrap/bundle-loader.c
mkdir -p out/darwin-bootstrap/safety-dance
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -Wno-unused-parameter -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/safety-dance/AutoGrid.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/safety-dance/AutoGrid.d ./darwin-bootstrap/safety-dance/AutoGrid.m
mkdir -p /opt/simject/Frameworks/substitute/out
ln -nfs libsubstitute.dylib /opt/simject/Frameworks/substitute/out/libsubstitute.0.dylib
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -o /opt/simject/Frameworks/substitute/out/unrestrict /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/darwin-bootstrap/unrestrict.o -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -dynamiclib -o /opt/simject/Frameworks/substitute/out/safemode-ui-hook.dylib /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/darwin-bootstrap/safemode-ui-hook.o -framework Foundation -framework UIKit -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p out/darwin-bootstrap/safety-dance
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -Wno-unused-parameter -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/safety-dance/main.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/safety-dance/main.d ./darwin-bootstrap/safety-dance/main.m
mkdir -p /opt/simject/Frameworks/substitute/out/SafetyDance.app
plutil -convert binary1 -o /opt/simject/Frameworks/substitute/out/SafetyDance.app/Info.plist ./darwin-bootstrap/safety-dance/Info.plist
mkdir -p out/darwin-bootstrap
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -Werror -I./lib -I./substrate -I./vendor -fobjc-arc -fvisibility=hidden -g -O3 -miphoneos-version-min=11.0 -Wno-error -c -o out/darwin-bootstrap/substituted.o -MMD -MF /opt/simject/Frameworks/substitute/out/darwin-bootstrap/substituted.d ./darwin-bootstrap/substituted.m
mkdir -p /opt/simject/Frameworks/substitute/out/SafetyDance.app
cp ./darwin-bootstrap/safety-dance/white.png /opt/simject/Frameworks/substitute/out/SafetyDance.app/Default.png
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -dynamiclib -o /opt/simject/Frameworks/substitute/out/bundle-loader.dylib out/darwin-bootstrap/bundle-loader.o -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p /opt/simject/Frameworks/substitute/out/SafetyDance.app
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -o /opt/simject/Frameworks/substitute/out/SafetyDance.app/SafetyDance out/darwin-bootstrap/safety-dance/AutoGrid.o out/darwin-bootstrap/safety-dance/main.o -framework UIKit -framework Foundation -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -dynamiclib -o /opt/simject/Frameworks/substitute/out/posixspawn-hook.dylib /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/darwin-bootstrap/posixspawn-hook.o -lbsm -dead_strip -O3 -miphoneos-version-min=11.0
mkdir -p /opt/simject/Frameworks/substitute/out
/usr/bin/xcrun --sdk iphonesimulator cc -arch x86_64 -o /opt/simject/Frameworks/substitute/out/substituted /opt/simject/Frameworks/substitute/out/libsubstitute.dylib out/darwin-bootstrap/substituted.o -lbsm -framework Foundation -framework CoreFoundation -dead_strip -O3 -miphoneos-version-min=11.0
Symlink CydiaSubstrate.framework for all installed iOS runtimes...
Symlink to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
find: /Library/Developer/CoreSimulator/Profiles/Runtimes: No such file or directory`

**Comment by baxttter** [comment]
I'm having the same issue. Not really sure how to fix it. Has it got to do with the Xcode version?

**Comment by PoomSmart** [comment]
Fixed in b97079d2932e4568aca6673347f6a2ef1f00c666
