### ISSUE TITLE
Issue when running ./configure

### ISSUE THREAD

**Issue by shulkk** [akemin-dayo/simject#80]
I get this error:
```console
 › ./configure --xcode-sdk=iphonesimulator --xcode-archs=x86_64 && make
Traceback (most recent call last):
  File "/Users/shulkk/simject/simject/substitute/./configure", line 4, in <module>
    import mconfig
  File "/Users/shulkk/simject/simject/substitute/./script/mconfig.py", line 1, in <module>
    import re, argparse, sys, os, string, shlex, subprocess, glob, parser, hashlib, json, errno
ModuleNotFoundError: No module named 'parser'
```
Maybe this has to do with something on issue #64? I'm on ARM64 macOS 12.3.1

**Comment by sugiuta** [comment]
I also faced that problem, but was able to solve it by changing the Python version to 3.8.

**Comment by shulkk** [comment]
Hm weird.. I'm on Python 3.10

**Comment by PoomSmart** [comment]
`parser` module has been removed in Python 3.10 (https://peps.python.org/pep-0617/)

Create an issue in https://github.com/sbingner/substitute because that's where the error is originated.
