### ISSUE TITLE
FLEX

### ISSUE THREAD

**Issue by itsmylife44** [akemin-dayo/simject#81]
is there any possibility to load flex as dylib into the ios simulator to debug the springboard for example ?

**Comment by akemin-dayo** [comment]
Yes, you should be able to perform runtime inspection via FLEX with simject as long as you compile [FLEXing](https://github.com/NSExceptional/FLEXing.git) and [libflex](https://github.com/NSExceptional/FLEXing/tree/master/libflex) using the iOS Simulator as a target.
