### ISSUE TITLE
`CydiaSubstrate.framework` installation doesn't work as of iOS 17 beta in macOS Sonoma

### ISSUE THREAD

**Issue by PoomSmart** [akemin-dayo/simject#82]
An iOS 17 beta simulator runtime root directory (under macOS Sonoma) is mounted as a volume under `/Library/Developer/CoreSimulator/Volumes/iOS_<BuildNumber>`. This volume is read-only so there's currently no way to install `CydiaSubstrate.framework` to it yet.

**Comment by lindo-zy** [comment]
Mac os 15,xcode 16
i use the simulator ios16.1,but it not work。
![image](https://github.com/user-attachments/assets/dec699e2-0c5c-4464-af52-e701824bf60c)
![image](https://github.com/user-attachments/assets/3fb590d1-4ca4-4969-95ef-436a77f1c19a)

**Comment by PoomSmart** [comment]
Fixed in the latest commit, with `mount_tmpfs` approach.
