### ISSUE TITLE
Error compiling `cydiasubstrate.framework` as of Somona 14.5

### ISSUE THREAD

**Issue by OffsetParts** [akemin-dayo/simject#86]
When trying to compile the framework with this command

`./configure --xcode-sdk=iphonesimulator --xcode-archs=$(uname -m) && make`

it errors in not finding the ldid component in the iphonesimulator sdk.

I don't know if its removed or how to readd it on on xcode 15.4 and the sdk is at 17.5

<img width="1680" alt="Screenshot 2024-06-03 at 12 15 26 PM" src="https://github.com/akemin-dayo/simject/assets/44343694/5512081b-c996-4faa-b20a-dd8a736bda9d">

**Comment by newpolygons** [comment]
Seems like you don't have ldid installed or it isn't in the right place. Try running "brew install ldid" if you are on mac.

**Comment by newpolygons** [comment]
Did you go through the process of installing Theos on the machine? I know ldid would have been a requirement for that I'm assuming this may be due to another package that could be missing. Also see the pinned issue on this repo I believe your MacOS/XCode versions are incompatible at the moment.

**Comment by PoomSmart** [comment]
Updated substitute to fix this issue.
