### ISSUE TITLE
env: python3.9: No such file or directory

### ISSUE THREAD

**Issue by lindo-zy** [akemin-dayo/simject#89]
cmd :./configure --xcode-sdk=iphonesimulator --xcode-archs=$(uname -m) && make
**error:env: python3.9: No such file or directory**

my device :macos15,xcode16.1

I am a beginner in tweak development, driven by interest. I want to debug tweak on simulator and need your assistance. Thank you.

**Comment by PoomSmart** [comment]
Try opening Terminal then installing Python 3.9

```
brew install python@3.9
```

**Comment by lindo-zy** [comment]
thank you poomsmart,you are so nice ,it work。 I thought it was a script problem，because my Mac comes with python3.9，i make a mistake。
